# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ECE 5210
tagline: Course webpage for ECE 5210 at Weber State University
description: Course webpage for ECE 5210 at Weber State University
author: Erc Gibbons
course_documents_url: &course_docs_url https://github.com/wsu-ece5210/course-documents
# baseurl: "/ece5210" # the subpath of your site, e.g. /blog
# url: "https://kevinl.info" # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
# remote_theme: just-the-docs/just-the-docs@v0.10.1
# nav_external_url is not supported in v0.10.1, so we need to update the theme
remote_theme: just-the-docs/just-the-docs
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  # Course Documents: "https://github.com/wsu-ece2260/course-documents"
  Eric Gibbons: "https://faculty.weber.edu/ericgibbons"
footer_content:

# Math settings
just_the_docs_mathjax: true

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ""
      type: staffers
    values:
      layout: staffer
      height: 300px
      subpath: "/assets/images/"
      width: 300px
  - scope:
      path: ""
      type: modules
    values:
      layout: module
  - scope:
      path: ""
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ""
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

nav_external_links:
  - title: Course Documents
    url: *course_docs_url
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false
